version: '3.4'

services:
  asv_perception_core:
    build:
      context: .
      dockerfile: Dockerfile-core
    image: asv_perception_core
    container_name: asv_perception_core
    tmpfs:
      - /tmp
    network_mode: host
    environment:
      - ROS_IP=0.0.0.0

  marine_perception_classification:
    build:
      context: .
      dockerfile: Dockerfile-classification
    image: asv_perception_classification
    container_name: asv_perception_classification
    tmpfs:
      - /tmp
    network_mode: host
    depends_on:
      - asv_perception_core
    volumes:  #debug:  map src directory to container so we don't have to rebuild
      - type: bind
        source: ./classification/asv_perception_classification
        target: /catkin_ws/src/asv_perception_classification
      #- type: bind
      #  source: ./classification/data
      #  target: /app/src/data
    environment:
      - ROS_MASTER_URI=http://0.0.0.0:11311/